"""People worth asking for a referral, and what happened with each.

A JSON overlay beside the tracker rather than a column in it, for the same
reason `sponsor_aliases.json` is: the workbook is regenerated by the 09:00 run,
and a contact is a human decision that must survive that. It is also a different
shape — one company has many contacts, one contact relates to several jobs — and
forcing that into a spreadsheet row would mean losing something.

Gitignored. These are real people with real names, and they do not belong in a
public repository.
"""
from __future__ import annotations

import json
import os
import threading
import uuid
from datetime import date
from pathlib import Path

STATUSES = ("found", "contacted", "replied", "referred", "declined")


class Contacts:
    def __init__(self, path: Path):
        self.path = Path(path)
        self._lock = threading.RLock()

    # --- reading ------------------------------------------------------------

    def all(self) -> list[dict]:
        if not self.path.exists():
            return []
        try:
            data = json.loads(self.path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            # A corrupt overlay must not take the app down; it degrades to
            # "no saved contacts", which is recoverable, unlike a crash loop.
            return []
        return data if isinstance(data, list) else data.get("contacts", [])

    def for_company(self, company: str) -> list[dict]:
        key = (company or "").strip().lower()
        return [c for c in self.all()
                if (c.get("company") or "").strip().lower() == key]

    def get(self, contact_id: str) -> dict | None:
        return next((c for c in self.all() if c.get("id") == contact_id), None)

    # --- writing ------------------------------------------------------------

    def _save(self, rows: list[dict]) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        tmp = self.path.with_suffix(".tmp")
        tmp.write_text(json.dumps(rows, indent=2, ensure_ascii=False),
                       encoding="utf-8")
        os.replace(tmp, self.path)          # atomic on-volume

    def upsert(self, *, company: str, name: str, source: str,
               handle: str = "", url: str = "", location: str = "",
               signals: list[str] | None = None, job_id: str = "",
               notes: str = "") -> dict:
        """Add a contact, or fold new information into one already recorded.

        Keyed on (company, handle-or-name) so saving the same person twice from
        two different jobs links both rather than creating a duplicate — which
        is the difference between "I have contacted this person" and "I have
        contacted this person twice by accident".
        """
        with self._lock:
            rows = self.all()
            key = (company.strip().lower(),
                   (handle or name).strip().lower())
            existing = next(
                (c for c in rows
                 if ((c.get("company") or "").strip().lower(),
                     ((c.get("handle") or c.get("name") or "").strip().lower()))
                 == key), None)

            if existing:
                if job_id and job_id not in existing.setdefault("job_ids", []):
                    existing["job_ids"].append(job_id)
                if notes.strip():
                    existing["notes"] = (
                        f"{existing.get('notes','')}\n{notes.strip()}".strip())
                for field, value in (("url", url), ("location", location),
                                     ("name", name)):
                    if value and not existing.get(field):
                        existing[field] = value
                self._save(rows)
                return existing

            row = {
                "id": uuid.uuid4().hex[:12],
                "company": company.strip(),
                "name": name.strip() or handle.strip(),
                "source": source,
                "handle": handle.strip(),
                "url": url.strip(),
                "location": location.strip(),
                "signals": signals or [],
                "status": "found",
                "job_ids": [job_id] if job_id else [],
                "notes": notes.strip(),
                "found_on": date.today().isoformat(),
                "contacted_on": "",
            }
            rows.append(row)
            self._save(rows)
            return row

    def set_status(self, contact_id: str, status: str,
                   note: str = "") -> dict | None:
        with self._lock:
            rows = self.all()
            row = next((c for c in rows if c.get("id") == contact_id), None)
            if row is None:
                return None
            row["status"] = status
            if status == "contacted" and not row.get("contacted_on"):
                row["contacted_on"] = date.today().isoformat()
            if note.strip():
                stamp = date.today().isoformat()
                row["notes"] = (
                    f"{row.get('notes','')}\n{stamp}: {note.strip()}".strip())
            self._save(rows)
            return row
